CREATE TABLE file_integrity_logs (

    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    file_name VARCHAR2(255),
    action VARCHAR2(255), -- 무결성 검사, 랜섬웨어 감염 여부, 안티디버깅 적용 여부 등
    status VARCHAR2(255), -- 성공, 실패, 감염됨 등 상태
    timestamp TIMESTAMP

);

CREATE TABLE file_signature_logs (

    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    file_name VARCHAR2(255),
    signature_before VARCHAR2(255),
    signature_after VARCHAR2(255),
    timestamp TIMESTAMP

);
